runtime: python312
automatic_scaling:
  target_cpu_utilization: 0.92
  # max_concurrent_request: 70
  target_throughput_utilization: 0.70
  max_instances: 1
entrypoint: gunicorn -b 0.0.0.0:8080 IPl_Dash:server